export interface StylePropertyDefinition {
  initial: string | number;
  inherited: boolean;
}

/**
 * Deterministic SVG/CSS property defaults used by the static renderer.
 * Values that need geometry, font, paint-server, or effect resolution remain
 * typed CSS strings until their feature resolver consumes them.
 */
export const STYLE_PROPERTY_DEFINITIONS = {
  "alignment-baseline": { initial: "auto", inherited: false },
  "baseline-shift": { initial: "baseline", inherited: false },
  clip: { initial: "auto", inherited: false },
  "clip-path": { initial: "none", inherited: false },
  "clip-rule": { initial: "nonzero", inherited: true },
  color: { initial: "black", inherited: true },
  "color-interpolation": { initial: "sRGB", inherited: true },
  "color-interpolation-filters": { initial: "linearRGB", inherited: true },
  "color-profile": { initial: "auto", inherited: true },
  "color-rendering": { initial: "auto", inherited: true },
  cursor: { initial: "auto", inherited: true },
  cx: { initial: 0, inherited: false },
  cy: { initial: 0, inherited: false },
  direction: { initial: "ltr", inherited: true },
  d: { initial: "none", inherited: false },
  display: { initial: "inline", inherited: false },
  "dominant-baseline": { initial: "auto", inherited: true },
  "enable-background": { initial: "accumulate", inherited: false },
  fill: { initial: "black", inherited: true },
  "fill-opacity": { initial: 1, inherited: true },
  "fill-rule": { initial: "nonzero", inherited: true },
  filter: { initial: "none", inherited: false },
  "flood-color": { initial: "black", inherited: false },
  "flood-opacity": { initial: 1, inherited: false },
  "font-family": { initial: "sans-serif", inherited: true },
  "font-feature-settings": { initial: "normal", inherited: true },
  "font-kerning": { initial: "auto", inherited: true },
  "font-size": { initial: 16, inherited: true },
  "font-size-adjust": { initial: "none", inherited: true },
  "font-stretch": { initial: "normal", inherited: true },
  "font-style": { initial: "normal", inherited: true },
  "font-variant": { initial: "normal", inherited: true },
  "font-weight": { initial: "normal", inherited: true },
  height: { initial: "auto", inherited: false },
  "glyph-orientation-horizontal": { initial: "0deg", inherited: true },
  "glyph-orientation-vertical": { initial: "auto", inherited: true },
  "image-rendering": { initial: "auto", inherited: true },
  isolation: { initial: "auto", inherited: false },
  kerning: { initial: "auto", inherited: true },
  "letter-spacing": { initial: "normal", inherited: true },
  "lighting-color": { initial: "white", inherited: false },
  "line-height": { initial: "normal", inherited: true },
  "marker-end": { initial: "none", inherited: true },
  "marker-mid": { initial: "none", inherited: true },
  "marker-start": { initial: "none", inherited: true },
  mask: { initial: "none", inherited: false },
  "mask-type": { initial: "luminance", inherited: false },
  "mix-blend-mode": { initial: "normal", inherited: false },
  opacity: { initial: 1, inherited: false },
  overflow: { initial: "visible", inherited: false },
  "paint-order": { initial: "normal", inherited: true },
  "pointer-events": { initial: "visiblePainted", inherited: true },
  r: { initial: 0, inherited: false },
  rx: { initial: "auto", inherited: false },
  ry: { initial: "auto", inherited: false },
  "shape-rendering": { initial: "auto", inherited: true },
  "solid-color": { initial: "black", inherited: false },
  "solid-opacity": { initial: 1, inherited: false },
  "stop-color": { initial: "black", inherited: false },
  "stop-opacity": { initial: 1, inherited: false },
  stroke: { initial: "none", inherited: true },
  "stroke-dasharray": { initial: "none", inherited: true },
  "stroke-dashoffset": { initial: 0, inherited: true },
  "stroke-linecap": { initial: "butt", inherited: true },
  "stroke-linejoin": { initial: "miter", inherited: true },
  "stroke-miterlimit": { initial: 4, inherited: true },
  "stroke-opacity": { initial: 1, inherited: true },
  "stroke-width": { initial: 1, inherited: true },
  "text-anchor": { initial: "start", inherited: true },
  "text-align": { initial: "start", inherited: true },
  "text-align-last": { initial: "auto", inherited: true },
  "text-decoration": { initial: "none", inherited: false },
  "text-decoration-color": { initial: "currentColor", inherited: false },
  "text-decoration-line": { initial: "none", inherited: false },
  "text-decoration-style": { initial: "solid", inherited: false },
  "text-indent": { initial: 0, inherited: true },
  "text-orientation": { initial: "mixed", inherited: true },
  "text-overflow": { initial: "clip", inherited: false },
  "text-rendering": { initial: "auto", inherited: true },
  transform: { initial: "none", inherited: false },
  "transform-box": { initial: "view-box", inherited: false },
  "transform-origin": { initial: "0 0", inherited: false },
  "unicode-bidi": { initial: "normal", inherited: false },
  "vector-effect": { initial: "none", inherited: false },
  "vertical-align": { initial: "baseline", inherited: false },
  visibility: { initial: "visible", inherited: true },
  "white-space": { initial: "normal", inherited: true },
  width: { initial: "auto", inherited: false },
  "word-spacing": { initial: "normal", inherited: true },
  "writing-mode": { initial: "horizontal-tb", inherited: true },
  x: { initial: 0, inherited: false },
  y: { initial: 0, inherited: false },
} as const satisfies Record<string, StylePropertyDefinition>;

export type StylePropertyName = keyof typeof STYLE_PROPERTY_DEFINITIONS;

export const StylePropertiesSet: ReadonlySet<string> = new Set(Object.keys(STYLE_PROPERTY_DEFINITIONS));

const PROPERTY_ALIASES: Readonly<Record<string, string>> = {
  clipPath: "clip-path",
  clipRule: "clip-rule",
  colorInterpolation: "color-interpolation",
  colorInterpolationFilters: "color-interpolation-filters",
  fillOpacity: "fill-opacity",
  fillRule: "fill-rule",
  floodColor: "flood-color",
  floodOpacity: "flood-opacity",
  fontFamily: "font-family",
  fontFeatureSettings: "font-feature-settings",
  fontKerning: "font-kerning",
  fontSize: "font-size",
  fontStretch: "font-stretch",
  fontStyle: "font-style",
  fontVariant: "font-variant",
  fontWeight: "font-weight",
  imageRendering: "image-rendering",
  letterSpacing: "letter-spacing",
  markerEnd: "marker-end",
  markerMid: "marker-mid",
  markerStart: "marker-start",
  maskType: "mask-type",
  mixBlendMode: "mix-blend-mode",
  paintOrder: "paint-order",
  pointerEvents: "pointer-events",
  shapeRendering: "shape-rendering",
  stopColor: "stop-color",
  stopOpacity: "stop-opacity",
  strokeDasharray: "stroke-dasharray",
  strokeDashoffset: "stroke-dashoffset",
  strokeLinecap: "stroke-linecap",
  strokeLinejoin: "stroke-linejoin",
  strokeMiterlimit: "stroke-miterlimit",
  strokeOpacity: "stroke-opacity",
  strokeWidth: "stroke-width",
  textAnchor: "text-anchor",
  textAlign: "text-align",
  textAlignLast: "text-align-last",
  textDecoration: "text-decoration",
  textDecorationColor: "text-decoration-color",
  textDecorationLine: "text-decoration-line",
  textDecorationStyle: "text-decoration-style",
  textIndent: "text-indent",
  textOrientation: "text-orientation",
  textOverflow: "text-overflow",
  textRendering: "text-rendering",
  transformBox: "transform-box",
  transformOrigin: "transform-origin",
  vectorEffect: "vector-effect",
  verticalAlign: "vertical-align",
  wordSpacing: "word-spacing",
  writingMode: "writing-mode",
};

/** Normalize CSS spelling and parser camel-case aliases to canonical kebab-case. */
export function canonicalPropertyName(name: string): string {
  const trimmed = name.trim();
  if (trimmed.startsWith("--")) return trimmed;
  const aliased = PROPERTY_ALIASES[trimmed];
  if (aliased) return aliased;
  return trimmed.replace(/[A-Z]/g, (letter) => `-${letter.toLowerCase()}`).toLowerCase();
}

export function isStyleProperty(name: string): name is StylePropertyName {
  return StylePropertiesSet.has(name);
}
