packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  eslint: 9.20.1
  prettier: 3.5.1
  typescript: 5.6.2
  tailwindcss: 3.4.4
  zod: 3.24.2
  "@types/node": 20.14.8
  postcss: 8.5.2
  tsup: 8.1.0
  "@next/mdx": ^14.2.23
  next: ^14.2.23
  eslint-config-next: ^14.2.23
  "@next/eslint-plugin-next": ^14.2.23

catalogs:
  react18:
    react: 18.3.1
    react-dom: 18.3.1
    "@types/react": 18.3.3
    "@types/react-dom": 18.3.0
