packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  eslint: 9.10.0
  prettier: 3.3.3
  typescript: 5.6.2
  tailwindcss: 3.4.4
  zod: 3.23.8
  "@types/node": 20.14.8
  postcss: 8.4.47
  tsup: 8.1.0

catalogs:
  react18:
    react: 18.3.1
    react-dom: 18.3.1
    "@types/react": 18.3.3
    "@types/react-dom": 18.3.0
